name: Publish module

on: [release]

jobs:
  publish_npm:
    name: Publish on NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Transform to NPM package
        run: deno task build_npm ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: Publish on NPM
        run: |
          cd npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
