name: Run Tests

on: [push, pull_request]

jobs:
  tests:
    name: Type-check code and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck code
        run: npm run typecheck

      - name: Run tests
        run: npm test

  formatting:
    name: Check formatting using Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Check formatting
        run: npx prettier --check .
