name: Run Tests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    name: Type-check code and run tests using Node ${{ matrix.node }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Type-check code
        run: deno check mod.ts

      - name: Run tests
        run: deno test --allow-none --doc

      - name: Lint code
        run: deno lint --compact
