name: Run Tests

on: [push, pull_request]

jobs:
  run_tests:
    name: Type-check code and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Type-check code
        run: deno check mod.ts

      - name: Type-check examples
        run: | 
          shopt -s globstar
          for f in examples/**/*.ts; do deno check $f; done

      - name: Run tests
        run: deno test --allow-none --doc

      - name: Lint code
        run: deno lint --compact
